var products = [
  {
    "product_id": "PR1000",
    "product_name": "KFC Chicken",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "yes",
    "sales_price": "0",
    "cost": "20",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "yes",
  },
  {
    "product_id": "PR1001",
    "product_name": "Italian Pizza",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "60",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },

];